---
secrets:
  ubibot_account_key:
    file: .secrets/ubibot-account-key
  sensors_rails_master_key:
    file: .secrets/sensors-rails-master-key
  sensors_db_password:
    file: .secrets/sensors-db-password
services:
  scheduler:
    image: ghcr.io/aaheiev/sensors:1.0.2-3
    platform: linux/amd64
    container_name: scheduler
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      RAILS_ENV: production
      DB_USER: sensors
      DB_PASSWORD_FILE: /run/secrets/sensors_db_password
      UBIBOT_ACCOUNT_KEY_FILE: /run/secrets/ubibot_account_key
      RAILS_MASTER_KEY_FILE: /run/secrets/sensors_rails_master_key
    command:
      - bundle
      - exec
      - clockwork
      - scheduler.rb
    secrets:
      - sensors_db_password
      - sensors_rails_master_key
      - ubibot_account_key
    healthcheck:
      test: ps aux | grep scheduler.rb | grep -v grep
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
