secrets:
  sensors_db_password:
    file: .secrets/sensors-db-password
  ubibot_account_key:
    file: .secrets/ubibot-account-key
services:
  scheduler:
    image: sensors:1.0.0
    build: .
    platform: linux/amd64
    restart: unless-stopped
#    stdin_open: true
#    tty: true
    command:
      - bundle
      - exec
      - clockwork
      - scheduler.rb
    environment:
      RAILS_ENV: production
      DB_PASSWORD_FILE: /run/secrets/sensors_db_password
      UBIBOT_ACCOUNT_KEY_FILE: /run/secrets/ubibot_account_key
    env_file:
      - .env
    secrets:
      - sensors_db_password
      - ubibot_account_key
#  ps aux | grep scheduler.rb | grep -v grep
