secrets:
  sensors_rails_master_key:
    file: config/master.key
  sensors_db_password:
    file: .secrets/sensors-db-password
  ubibot_account_key:
    file: .secrets/ubibot-account-key
services:
  scheduler:
    image: ghcr.io/aaheiev/sensors:1.0.1-36.1
#    build: .
    platform: linux/amd64
    restart: unless-stopped
#    stdin_open: true
#    tty: true
    command:
      - bundle
      - exec
      - clockwork
      - scheduler.rb
    environment:
      RAILS_ENV: production
      DB_NAME: sensors_dev
      DB_USER: sensors2
      DB_HOST: 192.168.118.106
      DB_PASSWORD_FILE: /run/secrets/sensors_db_password
      UBIBOT_ACCOUNT_KEY_FILE: /run/secrets/ubibot_account_key
      RAILS_MASTER_KEY_FILE: /run/secrets/sensors_rails_master_key
    secrets:
      - sensors_db_password
      - sensors_rails_master_key
      - ubibot_account_key
#  ps aux | grep scheduler.rb | grep -v grep
