secrets:
  sensors_db_password:
    file: .secrets/sensors-db-password
services:
  scheduler:
    image: sensors:1.0.0
    build: .
    platform: linux/amd64
    restart: unless-stopped
#    stdin_open: true
#    tty: true
    command:
      - bundle
      - exec
      - clockwork
      - scheduler.rb
    environment:
      RAILS_ENV: production
      DB_PASSWORD_FILE: /run/secrets/sensors_db_password
    env_file:
      - .env
    secrets:
      - sensors_db_password
