---
version: '3.9'
secrets:
  db_password:
    file: .secrets/db-password
  lockbox_master_key:
    file:                      .secrets/lockbox-master-key
  ubibot_account_key:
    file:                      .secrets/ubibot-account-key
services:
#  database:
#    image:                    timescale/timescaledb:latest-pg14-oss
#    environment:
#      POSTGRES_USER:          sensors
#      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
#      POSTGRES_DB:            sensors
#    volumes:
#      - database:/var/lib/postgresql/data
#    ports:
#      - 5432:5432
#    secrets:
#      - db_password
#    healthcheck:
#      test:                   ["CMD", "pg_isready", "-U", "sensors"]
#      interval:               5s
#      timeout:                5s
#      retries:                5
#    restart:                  unless-stopped
  scheduler:
    image:                     sensors:latest
    platform:                  linux/amd64
    environment:
      DB_HOST:                 192.168.118.106
      DB_NAME:                 sensors_dev
      DB_USER:                 sensors
      DB_PASSWORD_FILE:        /run/secrets/db_password
      LOCKBOX_MASTER_KEY_FILE: /run/secrets/lockbox_master_key
      UBIBOT_ACCOUNT_KEY_FILE: /run/secrets/ubibot_account_key
    command:
      - clockwork
      - scheduler.rb
    secrets:
      - db_password
      - lockbox_master_key
      - ubibot_account_key
    healthcheck:
      test:                    ["CMD", "ps aux | grep scheduler.rb | grep -v grep"]
      interval:                5s
      timeout:                 5s
      retries:                 5
    restart:                   unless-stopped
volumes:
  database:                   {}
