{
 "title": "Sensors (WS1)",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "grafana-postgresql-datasource" }
  ]
 },
 "panels": [
  { "title": "Temperature(℃)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Temperature inside (℃)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroup(m.created_at, '15m') AS \"time\",\n  ch.name AS metric,\n  m.value\nFROM measurements m join channels ch on ch.id = m.channel_id\nWHERE\n  $__timeFilter(m.created_at) AND\n  m.metric = 'Temperature ºC' AND\n  ch.sensor_type = 'WS1'AND\n  ch.location like '%inside%'\nORDER BY 1,2\n"
    }
   ]
  },
  {
   "title": "Temperature outside(℃)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroup(m.created_at, '15m') AS \"time\",\n  ch.name AS metric,\n  m.value\nFROM measurements m join channels ch on ch.id = m.channel_id\nWHERE\n  $__timeFilter(m.created_at) AND\n  m.metric = 'Temperature ºC' AND\n  ch.sensor_type = 'WS1'AND\n  ch.location like '%outside%'\nORDER BY 1,2"
    }
   ]
  },
  { "title": "Humidity(%)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Humidity Inside (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroup(m.created_at, '15m') AS \"time\",\n  ch.name AS metric,\n  m.value\nFROM measurements m join channels ch on ch.id = m.channel_id\nWHERE\n  $__timeFilter(m.created_at) AND\n  m.metric = 'Humidity' AND\n  ch.sensor_type = 'WS1'AND\n  ch.location like '%inside%'\nORDER BY 1,2\n"
    }
   ]
  },
  {
   "title": "Humidity Outside (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroup(m.created_at, '15m') AS \"time\",\n  ch.name AS metric,\n  m.value\nFROM measurements m join channels ch on ch.id = m.channel_id\nWHERE\n  $__timeFilter(m.created_at) AND\n  m.metric = 'Humidity' AND\n  ch.sensor_type = 'WS1'AND\n  ch.location like '%outside%'\nORDER BY 1,2\n"
    }
   ]
  },
  { "title": "Light(lux)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Light front side (lux)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "lux" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroup(m.created_at, '15m') AS \"time\",\n  ch.name AS metric,\n  m.value\nFROM measurements m join channels ch on ch.id = m.channel_id\nWHERE\n  $__timeFilter(m.created_at) AND\n  m.metric = 'Light' AND\n  ch.sensor_type = 'WS1' AND ch.name IN ( 'WS1 outside front', 'WS1 inside living room')\n\nORDER BY 1,2\n"
    }
   ]
  },
  {
   "title": "Light back side (lux)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "lux" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroup(m.created_at, '15m') AS \"time\",\n  ch.name AS metric,\n  m.value\nFROM measurements m join channels ch on ch.id = m.channel_id\nWHERE\n  $__timeFilter(m.created_at) AND\n  m.metric = 'Light' AND\n  ch.sensor_type = 'WS1' AND ch.name IN ( \n    'WS1 outside back', 'WS1 Pro top bedroom', 'WS1 Kateryna''s room', 'WS1 Kyrylo''s room'\n    )\n\nORDER BY 1,2\n"
    }
   ]
  },
  { "title": "Sensors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Voltage(V)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroup(m.created_at, '1h') AS \"time\",\n  ch.name AS metric,\n  m.value\nFROM measurements m join channels ch on ch.id = m.channel_id\nWHERE\n  $__timeFilter(m.created_at) AND\n  m.metric = 'Voltage' AND\n  ch.sensor_type = 'WS1'\nORDER BY 1,2\n"
    }
   ]
  },
  {
   "title": "WIFI RSSI(dBm)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroup(m.created_at, '15m') AS \"time\",\n  ch.name AS metric,\n  m.value\nFROM measurements m join channels ch on ch.id = m.channel_id\nWHERE\n  $__timeFilter(m.created_at) AND\n  m.metric = 'WIFI RSSI' AND\n  ch.sensor_type = 'WS1'\nORDER BY 1,2\n"
    }
   ]
  }
 ]
}