default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database:  <%= ENV['DB_NAME'] || 'sensors' %>
  username:  <%= ENV['DB_USER'] || 'sensors' %>
  password:  <%= begin IO.read(ENV.fetch("DB_PASSWORD_FILE")) rescue "" end %>
  host:      <%= ENV["DB_HOST"] %>
  # takes higher precedence than other settings
  url:       <%= ENV['DATABASE_URL'] %>
  reconnect: true

development:
  <<: *default

test:
  <<: *default
  database: sensors_test

production:
  <<: *default
