name: Docker Image CI

on:
  push:
    branches:
      - 6-deploy-dev
env:
  IMAGE_URL: ghcr.io/aaheiev/sensors
jobs:

  build:
    permissions: write-all
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.config.outputs.VERSION }}

    steps:
    - uses: actions/checkout@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Configure job
      id: config
      run: |
        APP_VERSION=$(cat VERSION)
        VERSION="${APP_VERSION}-dev.${{ github.run_number }}"
        echo "VERSION=$(echo $VERSION)" >> $GITHUB_ENV
        echo "VERSION=$(echo $VERSION)" >> $GITHUB_OUTPUT
        echo "VERSION=$(echo $VERSION)"

    - name: Show version
      run: |
        echo "VERSION: ${{ env.VERSION }}"

    - name: Build Docker image
      run: |
        docker build --build-arg build_version=${{ env.VERSION }} -t ${{ env.IMAGE_URL }}:${{ env.VERSION }} .

    - name: Publish Docker image
      run: |
        docker push ${{ env.IMAGE_URL }}:${{ env.VERSION }}

  deploy:
    permissions: write-all
    needs: [build]
    environment: dev
    runs-on:
      - self-hosted
      - bkouen
    env:
      VERSION: ${{ needs.build.outputs.VERSION }}
      DOCKER_COMPOSE_DIR: ../../../../../../${{ vars.DOCKER_COMPOSE_DIR }}
    steps:
      - name: Pull container image
        run: docker pull ${{ env.IMAGE_URL }}:${{ env.VERSION }}

      - name: Update docker-compose.yaml
        uses: fjogeleit/yaml-update-action@main
        with:
          valueFile: ${{ env.DOCKER_COMPOSE_DIR }}/docker-compose.yaml
          propertyPath: services.scheduler.image
          value: ${{ env.IMAGE_URL }}:${{ env.VERSION }}

      - name: Start app
        working-directory: ${{ env.DOCKER_COMPOSE_DIR }}
        run: |
          docker compose up -d
