name: Docker Image CI

on:
  push:
    branches:
      - 5-develop-ci

jobs:

  build:

#    runs-on: ubuntu-latest
    runs-on:
      - self-hosted
      - Linux
      - X64
      - bkouen

    steps:
    - uses: actions/checkout@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Configure job
      id: config
      run: |
        APP_VERSION=$(cat VERSION)
        VERSION="${APP_VERSION}-${{ github.run_number }}"
        echo "VERSION=$(echo $VERSION)" >> $GITHUB_ENV
        echo "VERSION=$(echo $VERSION)" >> $GITHUB_OUTPUT
        echo "VERSION=$(echo $VERSION)"

    - name: Show version
      run: |
        echo "VERSION: ${{ env.VERSION }}"

#    - name: Build the Docker image
#      run: |
#        docker build -t sensors .
#        docker build . --file Dockerfile --tag my-image-name:$(date +%s)

#    - name: Login container registry
#      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ secrets.WORKFLOWS_GITHUB_USER }}" --password-stdin

#    - name: Build the Docker image
#      run: |
#        docker build -t sensors .
#        docker build . --file Dockerfile --tag my-image-name:$(date +%s)
